# Welcome to xminy!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: xminy
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Super minimal, functional, and fast theme for Jekyll
meta_description: "xminy - xminy is minimal, functional and high performance theme for Jekyll. Supports dark mode."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ashisha
github_username:  ashisha
about: about.html

static_pages: [ about ]
markdown: kramdown
highlighter: rouge
logo: profile.png
paginate: 15
domain_name: "http://yourblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Ashish Anand"

# Disqus config
disqus-shortname: ""

# Build settings
theme: xminy

